# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eaa2d43c30e480b3e5513fd6b4a6a9f73f5ca7101c28d6c8221d56938c2700a2a0051b6e2d544cca497644602cdde1caa9f96f8a81326d65f93585c2b32a070
  devise_secret_key: 70672bb772727b644e9a9c67b4ae0a3fcafbe01b66b8da1b850b5651832a6e7f5eeef76039e2b4741b069d820a01e2fc223f1c89e66d83fd2fcc0de0a73f1695
  facebook_app_id: 880263821999011
  facebook_app_secret: 657d6280b5fa0861736068ea022ce939
  twitter_app_id: hlpYiJ4O6y4KUNgpB8ioKreIv
  twitter_app_secret: quwdV4T2SMswulMcvtqVleOMsjKSSM2Mi9BJZMVcpvWi9a00gn
  linkedin_app_id: 75ckmiz6dn856m
  linkedin_app_secret: dwZyKX8kQFUU6haO

test:
  secret_key_base: 283cc3c8b07a55736ec2d41bcd00613b31cc0c3320cc37622ba712a8b1508766c86a860247fe79140e368bc023db7a65cce1f628ec8fb5f6c88b71688f9312d0
  devise_secret_key: 70672bb772727b644e9a9c67b4ae0a3fcafbe01b66b8da1b850b5651832a6e7f5eeef76039e2b4741b069d820a01e2fc223f1c89e66d83fd2fcc0de0a73f1695
  facebook_app_id: 880263821999011
  facebook_app_secret: 657d6280b5fa0861736068ea022ce939
  twitter_app_id: hlpYiJ4O6y4KUNgpB8ioKreIv
  twitter_app_secret: quwdV4T2SMswulMcvtqVleOMsjKSSM2Mi9BJZMVcpvWi9a00gn
  linkedin_app_id: 75ckmiz6dn856m
  linkedin_app_secret: dwZyKX8kQFUU6haO

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
  linkedin_app_id: <%= ENV["LINKEDIN_APP_ID"] %>
  linkedin_app_secret: <%= ENV["LINKEDIN_APP_SECRET"] %>
